### PR TITLE
Setup pre-commit

### LINKED ISSUE #193: Use pre-commit hooks to apply linting rules
### Description

As noted in https://github.com/yt-project/unyt/pull/191#issuecomment-894608515 there are some PR that fail linter tests. As most of these linter tests just require a human to manually run a tool, like `flake8` or `black`, it seems like it would be helpful to use `pre-commit` hooks to run this for the user.

In my own projects what I've found super useful for keeping pre-commit hooks up to date and for saving time is to enable [pre-commit.ci](https://pre-commit.ci/) which will allow for pushes back to a PR if pre-commit hooks fail with attempts at resolving those failures.

There are some [examples over on the Scikit-HEP website](https://scikit-hep.org/developer/style#pre-commit) (in addition to all the examples the pre-commit team has).

### PR DESCRIPTION
**Pull request by neutrinoceros**
This is a proposal to close #193 and get unyt closer to yt in terms of tooling
It also upgrades styles with the newest (stable) version of black.

@jzuhone may I have your opinion on this ?

TODO:
- [x] documentation
- [x] cleanup (look for places where flake8 and black are referred and adapt or remove them)
- [ ] setup replacement for automated linting. Candidate tools
  - pre-commit.ci
  - tox + pre-commit
  - pre-commit GitHub action
  
  pre-commit.ci is the safest choice IMO and would keep unyt close to yt in terms of tooling.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
this PR is complete and ready for review. If we want to go this route we'll need to elect a new CI service to replace the linting tests, but that's not something that can be achieved as a pull request, so I'm opening now for discussions

**Comment by mattwthompson** [comment]
+1 for https://pre-commit.ci/

**Comment by neutrinoceros** [comment]
Thank you @jzuhone fir merging, but what about setting the CI part ?

**Comment by neutrinoceros** [comment]
I opened a new issue to make sure this doesn't get forgotten

**Comment by jzuhone** [comment]
@neutrinoceros Sounds good, hoping to get to it soon

**Pull request merged**
