### PR TITLE
make sure unit systems can be defined using unit objects. fixes #71

### LINKED ISSUE #71: Creating UnitSystem based on actual "units" doesn't appear to work in 2.0.0
* unyt version: 2.0.0
* Python version: 3.7.2
* Operating System: MacOS

### Description

I have a custom unit system, called `cosmological`, that I use for my thin i/o wrapper for SWIFT. It's defined in the following way:

```
import unyt

cosmo_units = unyt.UnitSystem(
    "cosmological", unyt.Mpc, 1e10 * unyt.msun, unyt.s * unyt.Mpc / unyt.km
)
```
This broke our test suite in `unyt2.0.0`.

### What I Did

Minimal breaking example below:
```
>>> import unyt
>>> unyt.UnitSystem("cosmological", "Mpc", "Msun", "s")
cosmological Unit System
 Base Units:
  length: Mpc
  mass: Msun
  time: s
  temperature: K
  angle: rad
  current_mks: A
  luminous_intensity: cd
 Other Units:
>>> unyt.UnitSystem("cosmologicalRealUnits", unyt.Mpc, unyt.Msun, unyt.s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mphf18/Documents/swift/swiftsimio/env/lib/python3.7/site-packages/unyt/unit_systems.py", line 218, in __init__
    bu = _split_prefix(unit, default_lut)[1]
  File "/Users/mphf18/Documents/swift/swiftsimio/env/lib/python3.7/site-packages/unyt/unit_systems.py", line 111, in _split_prefix
    possible_prefix = symbol_str[0]
TypeError: 'Unit' object does not support indexing
```
This seems to work fine if I pass strings, but if I pass real units then it doesn't work. This is a pain as I want to use 1e10 solar masses as my mass unit.

Am I doing something wrong here?

### PR DESCRIPTION
**Pull request by ngoldbaum**
ping @JBorrow

It looks like this may have used to work by accident. However it seems like a natural thing to want to do so I've explicitly added support for it, including docs and tests.

### CODE REVIEW

**Comment by JBorrow** [comment]
Hi, I'm not sure this is working quite yet:

```python
import unyt

unyt.UnitSystem("test", unyt.m, unyt.msun, unyt.s)
```

produces the following trace with `unyt2.1.0`:
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    unyt.UnitSystem("test", unyt.m, unyt.msun, unyt.s)
  File "/Users/mphf18/Documents/swift/swiftsimio/env/lib/python3.7/site-packages/unyt/unit_systems.py", line 227, in __init__
    raise IllDefinedUnitSystem(self.units_map)
unyt.exceptions.IllDefinedUnitSystem: Cannot create unit system with inconsistent mapping from dimensions to units. Received:
OrderedDict([((length), m), ((mass), unyt_quantity(1.98841586e+30, 'kg')), ((time), s), ((temperature), 'K'), ((angle), 'rad'), ((current_mks), 'A'), ((luminous_intensity), 'cd')])
```

**Comment by ngoldbaum** [comment]
That seems to be working on master. I should probably cut a new release.

**Comment by JBorrow** [comment]
Afaik this fix should have been included in `2.1.0`, and should be tested with https://github.com/yt-project/unyt/blob/ce9f04474e44c1b848ba73c0832f1ace2e2859f2/unyt/tests/test_unit_systems.py#L114. 

I don't think that test is sufficient. See the below:

Setup
------

`test.py`:
```python
import unyt
from unyt import unit_symbols as us

print("Testing creation based on unit_symbols")
unyt.UnitSystem("test", us.m, us.Msun, us.s)

print("Testing creation based on top-level units")
unyt.UnitSystem("test_units", unyt.m, unyt.msun, unyt.s)
```

Running the test
```
➜  /tmp python3 -m venv env
➜  /tmp source env/bin/activate
(env) ➜  /tmp pip3 install unyt 
...
Installing collected packages: mpmath, sympy, numpy, unyt
Successfully installed mpmath-1.1.0 numpy-1.16.3 sympy-1.4 unyt-2.2.0
...
(env) ➜  /tmp python3 test.py
Testing creation based on unit_symbols
Testing creation based on top-level units
Traceback (most recent call last):
  File "/private/tmp/env/lib/python3.7/site-packages/unyt/_parsing.py", line 89, in parse_unyt_expr
    unit_expr, global_dict=global_dict, transformations=unit_text_transform
  File "/private/tmp/env/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 966, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/private/tmp/env/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 879, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    Float ('1.98841586e+30' )Symbol ('kg' ,positive =True )
                                  ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    unyt.UnitSystem("test_units", unyt.m, unyt.msun, unyt.s)
  File "/private/tmp/env/lib/python3.7/site-packages/unyt/unit_systems.py", line 217, in __init__
    self.units_map[k] = parse_unyt_expr(str(v))
  File "/private/tmp/env/lib/python3.7/site-packages/unyt/_parsing.py", line 96, in parse_unyt_expr
    raise UnitParseError(msg)
unyt.exceptions.UnitParseError: Unit expression '1.98841586e+30 kg' raised an error during parsing:
SyntaxError('invalid syntax', ('<string>', 1, 31, "Float ('1.98841586e+30' )Symbol ('kg' ,positive =True )"))
(env) ➜  /tmp 
```

So it looks like creating these systems with the objects from `unyt.unit_systems` is fine, but not those from the top-level `unyt` library.

**Comment by ngoldbaum** [comment]
I'm able to reproduce a crash with the example in your latest comment, thanks!

**Comment by ngoldbaum** [comment]
So the issue is that `unyt.msun` is a quantity, not a unit object. We define both `unyt.unit_symbols.Msun` as well as `unyt.physical_constants.Msun`. The former is unit object while the latter is a quantity. Confusingly, we only define `unyt.physical_constants.msun`, not `unyt.unit_symbols.msun`.

So to fix this immediate issue, we probably want to add a check if we're passed a quantity and convert the quantity into a unit object. I don't see the harm in allowing people to pass in quantities if that's convenient for them and unit objects can be defined with constant multipliers.

The more general problem is that the way we've defined the solar units is annoying. I'm not totally sure what the best way to fix that is without breaking things so I'll be opening another issue to track that.

**Comment by JBorrow** [comment]
Thanks again for your extremely fast response and fix!

**Pull request merged**
