### PR TITLE
Add python-quantities to list of tested libraries in bench.py

### PR DESCRIPTION
**Pull request by thisch**
I couldn't find a package for perf on pypi, but I found [pyperf](https://github.com/vstinner/pyperf), which seems to have the same API as the perf library that was used in bench.py.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Yeah I think victor renamed the project, thank you for updating.

**Comment by thisch** [comment]
Thx for merging this! Note that I had to install an old version of pint (the one that is mentioned in the README.txt file) to fix problems in bench.py. For the other libraries (unyt, quantities, astropy) I installed the latest versions.

```
Traceback (most recent call last):
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_timeit.py", line 231, in bench_timeit
    runner.bench_time_func(name, timer.time_func, **kwargs)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_runner.py", line 458, in bench_time_func
    return self._main(task)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_runner.py", line 423, in _main
    bench = self._worker(task)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_runner.py", line 397, in _worker
    run = task.create_run()
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_worker.py", line 293, in create_run
    self.compute()
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_worker.py", line 331, in compute
    WorkerTask.compute(self)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_worker.py", line 280, in compute
    self.calibrate_loops()
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_worker.py", line 245, in calibrate_loops
    calibrate_loops=True)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_worker.py", line 76, in _compute_values
    raw_value = self.task_func(self, self.loops)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_runner.py", line 454, in task_func
    return time_func(loops, *args)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_timeit.py", line 125, in time_func
    return inner(it, timer)
  File "<timeit-src>", line 6, in inner
    np.power(data, 2, out=out)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pint/quantity.py", line 1531, in __array_ufunc__
    out = self._call_ufunc(ufunc, *inputs, **kwargs)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pint/quantity.py", line 1481, in _call_ufunc
    for other in inputs)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pint/quantity.py", line 1481, in <genexpr>
    for other in inputs)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pint/registry.py", line 711, in convert
    return self._convert(value, src, dst, inplace)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pint/registry.py", line 1242, in _convert
    return super(ContextRegistry, self)._convert(value, src, dst, inplace)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pint/registry.py", line 995, in _convert
    return super(NonMultiplicativeRegistry, self)._convert(value, src, dst, inplace)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pint/registry.py", line 733, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'dimensionless' (dimensionless) to 'gram' ([mass])
Traceback (most recent call last):
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_timeit.py", line 231, in bench_timeit
    runner.bench_time_func(name, timer.time_func, **kwargs)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_runner.py", line 458, in bench_time_func
    return self._main(task)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_runner.py", line 428, in _main
    bench = self._master()
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_runner.py", line 556, in _master
    bench = Master(self).create_bench()
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_master.py", line 221, in create_bench
    worker_bench, run = self.create_worker_bench()
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_master.py", line 120, in create_worker_bench
    suite = self.create_suite()
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_master.py", line 110, in create_suite
    suite = self.spawn_worker(self.calibrate_loops, 0)
  File "/opt/miniconda/envs/ims_py3/lib/python3.7/site-packages/pyperf/_master.py", line 97, in spawn_worker
    % (cmd[0], exitcode))
RuntimeError: /opt/miniconda/envs/ims_py3/bin/python failed with exit code 1
```
Do we want to keep support for the pint version mentioned in README.txt or are we allowed to update it?

**Comment by ngoldbaum** [comment]
So the benchmark exists basically for the unyt paper and hasn’t been updated since. If you’d like to improve it or update it go ahead. It’d be interesting to see if the performance claims I made in the JOSS paper still hold up.

**Comment by thisch** [comment]
> So the benchmark exists basically for the unyt paper and hasn’t been updated since. If you’d like to improve it or update it go ahead. It’d be interesting to see if the performance claims I made in the JOSS paper still hold up.

Thx. I'll create a new PR for it.

**Pull request merged**
