### PR TITLE
ENH: (NEP 18) implement numpy.savetxt

### PR DESCRIPTION
**Pull request by neutrinoceros**
for context, see discussion in #289, starting in https://github.com/yt-project/unyt/issues/289#issuecomment-1314196723

opening as a draft because it will inevitably conflict with #324

### CODE REVIEW

**Comment by neutrinoceros** [comment]
the first run failed with "did not warn", but I think that's just because warnings are filtered with `-W once` in the minimal env test job.

**Comment by neutrinoceros** [comment]
more tweaking needed, I'll come back to this later today

**Review by ngoldbaum — APPROVED** [review]
LGTM, let me know if this is safe to merge.

**Comment by neutrinoceros** [comment]
It is

**Comment by neutrinoceros** [comment]
Oops sorry I thought it was a different PR. I was planning to wait on #324 but you can merge this first if you'd like

**Comment by ngoldbaum** [comment]
Can you fix the conflicts?

**Comment by neutrinoceros** [comment]
@ngoldbaum done

**Pull request merged**
