### PR TITLE
TST: (NEP 18) auto mark deprecated (pure Python) functions as noop

### LINKED ISSUE #427: 3 new wrappable functions (NEP 18)
### Description

bleeding-edge CI is currently failing because numpy has 3 new wrappable functions
- `np.byte_bounts`
- `np.who`
- `np.safe_eval` (unreleased ?)

The first two are probably good left unwrapped, but `np.safe_eval` isn't documented yet (probably new in numpy dev). I'll dig further in later.

### PR DESCRIPTION
**Pull request by neutrinoceros**
closes #427

### CODE REVIEW

**Comment by neutrinoceros** [comment]
I validated that this passes bleeding-edge CI on my fork: https://github.com/neutrinoceros/unyt/actions/runs/5332044751

**Comment by neutrinoceros** [comment]
Heck, let's update the bleeding-edge workflow too while I'm at it (using nightlies instead of building numpy and matplotlib from source). This will save time and trigger validation here.

**Comment by neutrinoceros** [comment]
@ngoldbaum @jzuhone sorry I've been kinda stacking those up lately. Can this PR, or the problem it's aimed to solve, be prioritised ? I'm getting daily notifications about failed scheduled jobs.

**Comment by neutrinoceros** [comment]
Trying my luck again @jzuhone @ngoldbaum

**Review by jzuhone — APPROVED** [review]

**Pull request merged**
