### PR TITLE
fix: regression in lookup table (aliases for Msun)

### PR DESCRIPTION
**Pull request by neutrinoceros**
This fixes a regression reported in yt's main repo https://github.com/yt-project/yt/issues/2704

many thanks to @Xarthisius for figuring this out !

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I have my own fix for this which I'm going to issue separately.

**Comment by neutrinoceros** [comment]
Oops sorry Nathan I though I closed it myself by accident !

**Comment by ngoldbaum** [comment]
See #155. Sorry for closing your PR, I wanted to make sure the test got included as I had it in the diff I was working on when you issued this and didn't want to deal with adding you as a remote and doing back-and-forth on your branch.

**Comment by neutrinoceros** [comment]
No problem 😄

**Pull request closed without merging**
