### PR TITLE
BUG: multiple fixes for unyt_quantity.from_string

### LINKED ISSUE #361: unyt_quantity.from_string not working on simple expressions, e.g. "g**2/cm**2"
I cannot evaluate simple expressions such as "g\*\*2/cm\*\*2" with` unyt_quantity.from_string`. What am I missing?

```python
import unyt
print(unyt.__version__) # 'v2.9.3'
print(unyt.unyt_quantity.from_string("1e-3 g/cm**3"))  # correct: '0.001 g/cm**3' (taken from docs)
print(unyt.unyt_quantity.from_string("1e-3 g**2 / cm**2")) # wrong: '0.001 g**2'
print(unyt.unyt_quantity.from_string("g/cm**2")) # correct: '1 g/cm**2'
print(unyt.unyt_quantity.from_string("1 g**2/cm**2")) # wrong: '1.0 g**2'
print(unyt.unyt_quantity.from_string("g**2/cm**2")) # ValueError: Received invalid quantity expression 'g**2/cm**2'.
```

* unyt version: v2.9.3
* Python version: 3.9.7
* Operating System: debian 11

### PR DESCRIPTION
**Pull request by neutrinoceros**
fix #361

I would like to backport this to the 2.9.x branch and ship it as unyt 2.9.4

### CODE REVIEW

**Comment by neutrinoceros** [comment]
ping @jzuhone @ngoldbaum

**Comment by neutrinoceros** [comment]
I'll make sure that round tripping is also covered while I'm at it. Switching to draft until I figure it out.

**Comment by neutrinoceros** [comment]
found more broken test cases... I'm not giving up yet.

**Comment by neutrinoceros** [comment]
trying my luck again: can I get anyone to sign off here ? @ngoldbaum @jzuhone

**Comment by ngoldbaum** [comment]
Rather than trying to get the regex to work as we discover more cases that are broken, wouldn't it be simpler to just parse the input quantity as a number and unit, then pass the unit string we discover to the `Unit` initializer? Then the parser in there can decide if the unit is valid or not.

I don't think I was participating in unyt development when this feature was added, otherwise I would have suggested this then.

**Comment by neutrinoceros** [comment]
Well I'm not opposed to the refactor you are suggesting, but I'm not sure it would still qualify as a bugfix. Maybe we can preserve the spirit of the existing code on the backport branch and attempt a refactor on the dev branch ?

**Comment by ngoldbaum** [comment]
I don't personally think it matters much, but if you don't want to do that then fine. I don't see any issues with this code. Feel free to merge and do backports if you'd like.

**Comment by neutrinoceros** [comment]
I think you have a point: it *is* too complex. I'll consider refactoring it.

**Comment by munkm** [comment]
Was there an approving review on this PR before it got merged?

**Comment by matthewturk** [comment]
Yes.

> I don't personally think it matters much, but if you don't want to do that then fine. I don't see any issues with this code. Feel free to merge and do backports if you'd like.

**Comment by munkm** [comment]
Ok, thanks!

**Pull request merged**
