### PR TITLE
TST: reduce bleeding edge testing frequency from daily to weekly

### PR DESCRIPTION
**Pull request by neutrinoceros**
In hindsight, daily testing seems like overkill.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
failures are unrelated and fixed in #486

**Review by chrishavlin — APPROVED** [review]
agreed!

**Comment by chrishavlin** [comment]
oh, whoops, haha, thought i was in yt here! since i haven't been in unyt much lately maybe wait for approval from others :)

**Comment by neutrinoceros** [comment]
no worries. For what it's worth yt is already on a weekly schedule :)

**Pull request merged**
