### PR TITLE
TST: pin tox<4.0 to workaround incompatibility with tox-pyenv

### PR DESCRIPTION
**Pull request by neutrinoceros**
This PR isn't meant to be merged. Rather, I intend to use it as a playground to discover bugs with the upcoming new major release of tox. Best case scenario nothing breaks and we can close this.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
turns out we *do* have an issue here, in that `tox-pyenv` depends on the `py` library, but doesn't declare it explicitly as a dependency. It *used* to work because `tox` itself had `py` as a dependency but it looks like it's going to be dropped in `tox` 4.0

I will report this upstream to `tox-pyenv`, but the project looks very much unmaintained (no updates at all in 5 years), so I'm don't have much hope of getting an answer there.

**Comment by ngoldbaum** [comment]
I guess we could vendor it if it's unmaintained, I think the uses of `py` are pretty easy to patch out so we don't need to depend on that.

**Comment by neutrinoceros** [comment]
Actually I have hopes it might get answered as one of the maintainers also works very actively on tox itself. Hopefully we don't need to vendor this anything 🤞

**Comment by neutrinoceros** [comment]
tox 4.0 final was just released, I assume its too late to get the smooth transition I was hoping for
https://github.com/tox-dev/tox/releases/tag/4.0.0

**Comment by neutrinoceros** [comment]
yup. Now CI is plain broken... I opened a cross ref on the main repo https://github.com/tox-dev/tox/issues/2611

**Comment by neutrinoceros** [comment]
Going for it

**Pull request merged**
