### PR TITLE
TST: minimize build time in tox runs

### PR DESCRIPTION
**Pull request by neutrinoceros**
Just learned that tox 4 allows universal wheels to be built once and reused across multiple envs, reducing the build time to a minimum.
https://tox.wiki/en/latest/upgrading.html#universal-wheels

### CODE REVIEW

**Comment by neutrinoceros** [comment]
This seems to save about 40% overhead on the Python 3.8 job in CI, but that's it, because it's the only job with multiple tasks to run. Probably still worth it.

Also fixed an issue with `testenv:end` where coverage was run without toml support and crashed.

**Comment by neutrinoceros** [comment]
Apparently `setup-python` now supports setting multiple python versions in a single job
https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#specifying-multiple-pythonpypy-version
Switching to draft while I attempt to leverage this here

**Comment by jzuhone** [comment]
Is this still worth it, considering we're probably going to drop Python 3.8 soon?

**Comment by neutrinoceros** [comment]
I think so. The workload currently carried by Python 3.8 will eschew to 3.9 and we'll also add 3.12 when enough of our test dependencies support it, so I don't think this cycle is going to change much in itself.

**Pull request merged**
