### PR TITLE
Utilize github actions

### PR DESCRIPTION
**Pull request by matthewturk**
This pull request implements github actions.

The errors that are showing up need to be fixed, which I will do in a separate PR.  Before this goes in, the travis and appveyor configurations should be removed.  Additionally, this should probably be squashed when it goes in.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@matthewturk I see that you're using `tox` here. I've never tried to use `tox` in GitHub Actions and have just relied on having the build matrix and the `setup-python` action do the work, but it is possible to test using `tox` and GHA.

- The GHA docs have a section on that: [Running tests with tox](https://docs.github.com/en/actions/guides/building-and-testing-python#running-tests-with-tox)
- and seems like there's at least on custom GHA that delivers a more `tox`-y like experience: https://github.com/ymyzk/tox-gh-actions

**Comment by matthewfeickert** [comment]
Looks like from the logs like Black needs to get run and a `docstest` issue of unrunable code in a snippet in [`docs/usage.rst`](https://github.com/yt-project/unyt/blob/aaa2b244207c14c5f472214595a00201d105c0ae/docs/usage.rst#hdf5-files) that is keeping the CI from passing as is. So the following won't _pass_ CI, but it will run all of it.

```console
$ cat .github/workflows/ci.yml
```
```yaml 
name: CI

on:
  push:
    branches:
    - master
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'
  workflow_dispatch:


jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        # Test all on ubuntu, test ends on macos and windows
        exclude:
          - os: macos-latest
            python-version: 3.7
          - os: macos-latest
            python-version: 3.8
          - os: windows-latest
            python-version: 3.7
          - os: windows-latest
            python-version: 3.8


    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox and any other packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install tox tox-pyenv coverage
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py -vvv
```

**Comment by jzuhone** [comment]
I'm going to merge this so @matthewfeickert can rebase his PR on it.

**Comment by matthewfeickert** [comment]
> I'm going to merge this so @matthewfeickert can rebase his PR on it.

Oh, my PR is basically going to clobber all of this as this CI fails.

**Pull request merged**
